version: '3'
services:
  master:
    image: 'bitnami/spark:3.3.2-debian-11-r134'
    ports:
      - '7077:7077'
      - '7078:8082'
    environment:
      - SPARK_MODE=master
      #- CUSTOMER_MASTER_KEY=fd97c8e0-2d13-4b02-8fe4-be8334ead77e
      - CUSTOMER_MASTER_KEY=${CUSTOMER_MASTER_KEY}
    env_file:
      - /home/parasharprasoon_950/common.env
    volumes:
      - ".:/test-files:rw"
    networks:
      - my-network
  worker1:
    image: 'bitnami/spark:3.3.2-debian-11-r134'
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    networks:
      - my-network
  worker2:
    image: 'bitnami/spark:3.3.2-debian-11-r134'
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
    networks:
      - my-network


networks:
  my-network:
    external: true